=== TechnologyBrewery/fermenter/fermenter-mda/src/main/resources/fermenter-2-service-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "#service",
	"title": "Service",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"name": {
			"type": "string"
		},
		"package": {
			"type": "string"
		},
		"documentation": {
			"type": "string"
		},
		"operations": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"documentation": {
						"type": "string"
					},
					"transactionAttribute": {
						"type": "string"
					},
					"compressedWithGzip": {
						"type": "boolean"
					}
				},
				"return": {
					"type": "object",
					"properties": {
						"type": {
							"type": "string"
						},
						"package": {
							"type": "string"
						},
						"many": {
							"type": "boolean"
						},
						"responseEncoding": {
							"type": "string"
						}			
					},
					"required": [
						"type"
					]
				},
				"parameters": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"type": {
								"type": "string"
							},
							"package": {
								"type": "string"
							},
							"many": {
								"type": "boolean"
							},
							"documentation": {
								"type": "string"
							}					
						},
						"required": [
							"name", "type"
						]
					}
				}
			},
			"required": [
				"name", "return"
			]
		}
	},
	"required": [
		"name", "package", "operations"
	]
}

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/services/ContractTest.json
{
	"package": "org.bitbucket.askllc.fermenter.cookbook.domain",
	"name": "ContractTest",
	"documentation": "Operations to help test various generation permutations for generation test coverage",
	"operations": [
		{
			"name": "voidResponseMethod",
			"parameters": [],
			"return": {
				"type": "void"
			}
		},
		{
			"name": "stringResponseMethod",
			"parameters": [],
			"return": {
				"type": "string"
			}
		},
		{
			"name": "entityResponseMethod",
			"parameters": [],
			"return": {
				"type": "SimpleDomain"
			}
		},
		{
			"name": "enumerationResponseMethod",
			"parameters": [],
			"return": {
				"type": "SimpleDomainEnumeration"
			}
		},
		{
			"name": "multipleStringsResponseMethod",
			"parameters": [],
			"return": {
				"type": "string",
				"many": true
			}
		},
		{
			"name": "multipleEntitiesResponseMethod",
			"parameters": [],
			"return": {
				"type": "SimpleDomain",
				"many": true
			}
		},
		{
			"name": "multipleStringsPagedResponseMethod",
			"parameters": [],
			"return": {
				"type": "string",
				"many": true,
				"pagedResponse": true
			}
		},
		{
			"name": "multipleEntitiesPagedResponseMethod",
			"parameters": [],
			"return": {
				"type": "SimpleDomain",
				"many": true,
				"pagedResponse": true
			}
		},
		{
			"name": "noParameterMethod",
			"parameters": [],
			"return": {
				"type": "void"
			}
		},
		{
			"name": "stringParameterMethod",
			"parameters": [
				{
					"name": "inputStr",
					"type": "string"
				}
			],
			"return": {
				"type": "void"
			}
		},
		{
			"name": "entityParameterMethod",
			"parameters": [
				{
					"name": "entity",
					"package": "org.bitbucket.askllc.fermenter.cookbook.domain",
					"type": "SimpleDomain",
					"documentation": "An entity parameter"
				}
			],
			"return": {
				"type": "void"
			}
		},
		{
			"name": "enumerationParameterMethod",
			"parameters": [
				{
					"name": "enumeration",
					"package": "org.bitbucket.askllc.fermenter.cookbook.domain",
					"type": "SimpleDomainEnumeration",
					"documentation": "An object that is a parameter"
				}
			],
			"return": {
				"type": "void"
			}
		},
		{
			"name": "entityAndStringParametersMethod",
			"parameters": [
				{
					"name": "inputStr",
					"type": "string"
				},
				{
					"name": "entity",
					"package": "org.bitbucket.askllc.fermenter.cookbook.domain",
					"type": "SimpleDomain",
					"documentation": "An entity parameter"
				}
			],
			"return": {
				"type": "void"
			}
		},
		{
			"name": "multipleStringParametersMethod",
			"parameters": [
				{
					"name": "inputStr",
					"type": "string",
					"many": true
				}
			],
			"return": {
				"type": "void"
			}
		},
		{
			"name": "multipleEntitiesParameterMethod",
			"parameters": [
				{
					"name": "entity",
					"package": "org.bitbucket.askllc.fermenter.cookbook.domain",
					"type": "SimpleDomain",
					"documentation": "An entity parameter",
					"many": true
				}
			],
			"return": {
				"type": "void"
			}
		},
		{
			"name": "errorMessagesReturnedMethod",
			"parameters": [],
			"return": {
				"type": "void"
			}
		}
	]
}

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/services/SimpleDomainManager.json
{
  "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
  "name" : "SimpleDomainManager",
  "documentation" : "A collection of operations for the SimpleDomain",
  "operations" : [ {
    "name" : "GetSimpleDomainCount",
    "documentation" : "Returns the number of persistent SimpleDomains that\n\t\t\t\texist",
    "transactionAttribute" : "Supports",
    "parameters" : [ ],
    "return" : {
      "type" : "integer"
    }
  }, {
    "name" : "ReturnVoid",
    "parameters" : [ ],
    "return" : {
      "type" : "void"
    }
  }, {
    "name" : "CreateAndPropagateErrorMessages",
    "parameters" : [ {
      "name" : "numErrorMessagesToGenerate",
      "type" : "integer"
    } ],
    "return" : {
      "type" : "void"
    }
  }, {
    "name" : "SaveSimpleDomainEntityAndPropagateErrorMessages",
    "parameters" : [ {
      "name" : "targetNameValue",
      "type" : "string"
    }, {
      "name" : "numErrorMessagesToGenerate",
      "type" : "integer"
    } ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain"
    }
  }, {
    "name" : "SelectAllSimpleDomains",
    "transactionAttribute" : "Supports",
    "parameters" : [ ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "many" : true
    }
  }, {
    "name" : "DoSomethingWithPrimitiveInputs",
    "parameters" : [ {
      "name" : "inputStr",
      "type" : "string"
    }, {
      "name" : "inputInt",
      "type" : "integer"
    } ],
    "return" : {
      "type" : "void"
    }
  }, {
    "name" : "MethodWithSingleEntityAsParam",
    "documentation" : "When AeroGear deals with an object that has an id, it wants to use PUT vice POST",
    "transactionAttribute" : "Required",
    "parameters" : [ {
      "name" : "simpleDomain",
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "documentation" : "An object that is a parameter"
    } ],
    "compressedWithGZip" : true,
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain"
    }
  }, {
    "name" : "ReturnNullEntity",
    "parameters" : [ ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain"
    }
  }, {
    "name" : "SelectAllSimpleDomainsLazySimpleDomainChild",
    "transactionAttribute" : "Supports",
    "parameters" : [ ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "many" : true
    }
  }, {
    "name" : "DeleteAllSimpleDomains",
    "parameters" : [ ],
    "return" : {
      "type" : "void"
    }
  }, {
    "name" : "EchoPlusWazzup",
    "documentation" : "Returns your string concatenated with another, perhaps\n\t\t\t\tcooler, one",
    "parameters" : [ {
      "name" : "echoRoot",
      "type" : "string"
    } ],
    "return" : {
      "type" : "string"
    }
  }, {
    "name" : "SomeBusinessOperation",
    "documentation" : "An operation that demonstrates some important business\n\t\t\t\tfunction. Returns the altered domain.",
    "parameters" : [ {
      "name" : "someBusinessEntity",
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "documentation" : "The entity on which we should perform some business\n\t\t\t\t\t\toperation"
    }, {
      "name" : "otherImportantData",
      "type" : "string",
      "documentation" : "Critical data to supplement the business entity"
    } ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain"
    }
  }, {
    "name" : "CountNumInputs",
    "documentation" : "Returns the number of provided SimpleDomain entities",
    "parameters" : [ {
      "name" : "input",
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "many" : true
    } ],
    "compressedWithGZip" : true,
    "return" : {
      "type" : "integer"
    }
  }, {
    "name" : "SelectAllSimpleDomainsWithPaging",
    "transactionAttribute" : "Supports",
    "parameters" : [ {
      "name" : "startPage",
      "type" : "integer",
      "documentation" : "0-based start page"
    }, {
      "name" : "pageSize",
      "type" : "integer",
      "documentation" : "Maximum number of results to return"
    } ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "many" : true
    }
  }, {
    "name" : "ReturnManyPrimitives",
    "documentation" : "Returns a list of the given size with each element containing the provided integer",
    "parameters" : [ {
      "name" : "input",
      "type" : "integer"
    }, {
      "name" : "returnListSize",
      "type" : "integer"
    } ],
    "return" : {
      "type" : "integer",
      "many" : true
    }
  }, {
    "name" : "DoSomethingAndReturnAPrimitive",
    "parameters" : [ ],
    "return" : {
      "type" : "character"
    }
  }, {
    "name" : "SelectAllSimpleDomainsByDate",
    "parameters" : [ {
      "name" : "inputDate",
      "type" : "date"
    } ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "many" : true
    }
  }, {
    "name" : "SelectAllSimpleDomainsBeforeDate",
    "parameters" : [ {
      "name" : "inputDate",
      "type" : "date"
    } ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "many" : true
    }
  }, {
    "name" : "SelectAllSimpleDomainsAfterDate",
    "parameters" : [ {
      "name" : "inputDate",
      "type" : "date"
     } ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "many" : true
    }
  }, {
    "name" : "GetCountForDate",
    "parameters" : [ {
      "name" : "inputDate",
      "type" : "date"
     } ],
    "return" : {
      "type" : "integer"
    }
  }, {
    "name" : "ReturnVoidForDateInput",
    "parameters" : [ {
      "name" : "inputDate",
      "type" : "date"
     } ],
    "return" : {
      "type" : "void"
    }
  }, {
    "name" : "SelectAllSimpleDomainsByType",
    "transactionAttribute" : "Supports",
    "parameters" : [ {
      "name" : "type",
      "type" : "string"
    } ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "many" : true
    }
  }, {
	"name" : "UpdateAllSimpleDomainChildNames",
	"transactionAttribute" : "Required",
	"documentation" : "Sets the name of each lazily loaded SimpleDomainChild attached to the given to SimpleDomain to validate the ability to interact with lazily loaded objects using JTA-style simple accessors",
	"parameters" : [ {
      "name" : "simpleDomainId",
      "type" : "string"
    }, {
      "name" : "childName",
      "type" : "string"
    } ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain"
    }
  } ]
}

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/services/EnumerationBased.json
{
  "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
  "name" : "EnumerationBased",
  "documentation" : "A service that uses enumerations as inputs and outputs for test purposes",
  "operations" : [ {
    "name" : "PassInSingleEnumeratedValue",
    "parameters" : [ {
      "name" : "enumeratedValue",
      "package": "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomainEnumeration",
      "documentation" : "enumeration value"
    } ],
    "return" : {
      "type" : "void",
      "pagedResponse" : false
    }
  }, {
    "name" : "ReturnSingleEnumeratedValue",
    "transactionAttribute" : "Supports",
    "parameters" : [ ],
    "return" : {
      "package": "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomainEnumeration",
      "pagedResponse" : false
    }
  }, {
    "name" : "ReturnMultipleEnumeratedValue",
    "transactionAttribute" : "Supports",
    "parameters" : [ ],
    "return" : {
      "package": "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomainEnumeration",
      "many" : true,
      "pagedResponse" : false
    }
  }, {
    "name" : "PassInMultipleEnumeratedValues",
    "parameters" : [ {
      "name" : "enumeratedValue",
      "package": "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomainEnumeration",
      "many" : true,
      "documentation" : "enumeration value"
    } ],
    "return" : {
      "type" : "void",
      "pagedResponse" : false
    }
  } ]
}

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/services/ServiceExampleLogger.json
{
  "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
  "name" : "ServiceExampleLogger",
  "documentation" : "A service that logs standard and template methods",
  "operations" : [ {
    "name" : "LogServiceEntityExample",
    "parameters" : [],
    "return" : {
      "type" : "void"
    }
  } ]
}

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/services/Heartbeat.json
{
  "package": "org.bitbucket.askllc.fermenter.cookbook.domain",
  "name": "Heartbeat",
  "documentation": "An example of a supports/get service that returns a void response",
  "operations": [
    {
      "name": "Heartbeat",
      "documentation": "An example of a supports/get service that returns a void response",
      "transactionAttribute": "Supports",
      "parameters": [],
      "return": {
        "type": "void"
      }
    }
  ]
}

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-referencing-domain/src/main/resources/services/CrossReferenceExample.json
{
  "package" : "org.bitbucket.askllc.fermenter.cookbook.referencing.domain",
  "name" : "CrossReferenceExample",
  "documentation" : "A collection of operations that intermix local and remote metadata assets",
  "operations" : [ {
    "name" : "DoSomethingAndReturnARemoteEntity",
    "transactionAttribute" : "Supports",
    "parameters" : [ ],
    "return" : {
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "many" : true
    }
  }, {
    "name" : "DoSomethingWithARemoteEntityParam",
    "transactionAttribute" : "Supports",
    "parameters" : [ {
      "name" : "remoteEntity",
      "package" : "org.bitbucket.askllc.fermenter.cookbook.domain",
      "type" : "SimpleDomain",
      "documentation" : "A remote entity as an example"
    } ],
    "return" : {
      "type" : "LocalDomain",
      "many" : true
    }
  } ]
}
