=== TechnologyBrewery/fermenter/fermenter-mda/src/main/resources/fermenter-2-entity-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "#entity",
	"title": "Entity",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"name": {
			"type": "string"
		},
		"package": {
			"type": "string"
		},
		"documentation": {
			"type": "string"
		},
		"table": {
			"type": "string"
		},
		"transient": {
			"type": "boolean"
		},
		"parent": {
			"type": "object",
			"properties": {
				"package": {
					"type": "string"
				},
				"type": {
					"type": "string"
				},
				"inheritanceStrategy": {
					"type": "string"
				}			
			},
			"required": [
				"type"
			]
		},
		"identifier": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"type": {
					"type": "object",
					"properties": {
						"name": {
							"type": "string"
						}		
					},
					"required": [
						"name"
					]
				},
				"column": {
					"type": "string"
				},
				"documentation": {
					"type": "string"
				},
				"generator": {
					"type": "string"
				}
			},
			"required": [
				"name","type"
			]
		},
		"fields": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"type": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},						
							"package": {
								"type": "string"
							}		
						},
						"required": [
							"name"
						]
					},
					"column": {
						"type": "string"
					},
					"documentation": {
						"type": "string"
					},
					"required": {
						"type": "boolean"
					}
				},
				"required": [
					"name","type"
				]
			}
		},
		"references": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"type": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"package": {
								"type": "string"
							}	
						},
						"required": [
							"name"
						]
					},
					"localColumn": {
						"type": "string"
					},
					"documentation": {
						"type": "string"
					},
					"required": {
						"type": "boolean"
					}
				},
				"required": [
					"name","type"
				]
			}
		},
		"relations": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"type": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"package": {
								"type": "string"
							}	
						},
						"required": [
							"name"
						]
					},
					"localColumn": {
						"type": "string"
					},
					"documentation": {
						"type": "string"
					},
					"multiplicity": {
						"type": "string"
					},
					"fetchMode": {
						"type": "string"
					}
				},
				"required": [
					"name","type"
				]
			}
		}
	},
	"required": [
		"name", "package"
	]
}

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-referencing-domain-client/src/main/resources/entities/DoubleIndirectionDomain.json
{
  "package" : "org.bitbucket.askllc.fermenter.cookbook.referencing.domain",
  "name" : "DoubleIndirectionDomain",
  "documentation" : "A domain that reference an external domain that in turn references another external domain",
  "table" : "DOUBLE_INDIRECTION",
  "identifier" : {
    "name" : "id",
    "column" : "DOUBLE_INDIRECTION_ID",
    "type" : {
      "name" : "uuid"
    },
    "required" : true,
    "generator" : "uuid"
  }
}
