=== TechnologyBrewery/fermenter/fermenter-mda/src/main/resources/fermenter-2-entity.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT entity (name, namespace?, documentation?, parent?, table?, lockStrategy?, id?, fields?, composites?, associations?, queries?)>
<!ELEMENT namespace (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT documentation (#PCDATA)>

<!ELEMENT parent (type, inheritanceStrategy?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT inheritanceStrategy (#PCDATA)>

<!ELEMENT table (#PCDATA)>
<!ELEMENT lockStrategy (#PCDATA)>
<!ATTLIST entity transient CDATA "false">

<!ELEMENT id (field)>

<!ELEMENT fields (field+)>
<!ELEMENT field (name, documentation?, type, project?, column?, required?, generator?, maxLength?, minLength?, maxValue?, minValue?, scale?, label?, format?)>
<!ELEMENT column (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT generator (#PCDATA)>
<!ELEMENT maxLength (#PCDATA)>
<!ELEMENT minLength (#PCDATA)>
<!ELEMENT maxValue (#PCDATA)>
<!ELEMENT minValue (#PCDATA)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT format (#PCDATA)>

<!ELEMENT associations (reference*,relation*)>
<!ELEMENT reference (name?, documentation?, type, project?, fk?,required?)>
<!ELEMENT project (#PCDATA)>
<!ELEMENT fk (name,source,column?)>
<!ELEMENT source (#PCDATA)>

<!ELEMENT relation (documentation?, type, fk?, multiplicity, fetchMode?)>
<!ELEMENT multiplicity (#PCDATA)>
<!ELEMENT fetchMode (#PCDATA)>

<!ELEMENT queries (query+)>
<!ELEMENT query (name, documentation?, criteria?, pagination?, statement)>
<!ELEMENT criteria (criterion+)>
<!ELEMENT criterion (name, documentation?, type)>
<!ELEMENT statement (#PCDATA)>
<!ELEMENT pagination (#PCDATA)>

<!ELEMENT composites (composite*)>
<!ELEMENT composite (type, name?, project?, prefix?, label)>
<!ELEMENT prefix (#PCDATA)>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-referencing-domain-client/src/main/resources/entities/DoubleIndirectionDomain.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>DoubleIndirectionDomain</name>
	<namespace>org.bitbucket.askllc.fermenter.cookbook.indirection.domain</namespace>
	<documentation>A domain that reference an external domain that in turn references another external domain</documentation>
	<table>DOUBLE_INDIRECTION</table>

	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>DOUBLE_INDIRECTION_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>name</name>
			<documentation>The friendly domain moniker</documentation>
			<type>string</type>
			<column>NAME</column>
		</field>
	</fields>

	<associations>
		<reference>
			<name>externalDomain</name>
			<type>LocalDomain</type>
			<required>true</required>
		</reference>
	</associations>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/NonUUIDKeyEntity.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>NonUUIDKeyEntity</name>
	<documentation>Entity that uses a non-generated value primary key</documentation>
	<table>NON_UUID_KEY_ENTITY</table>

	<id>
		<field>
			<name>id</name>
			<type>string</type>
			<column>NON_UUID_KEY_ENTITY_ID</column>
			<required>true</required>
		</field>
	</id>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/BeerExampleEntity.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>BeerExampleEntity</name>
	<documentation>Entity to help with the Getting Started Guide</documentation>
	<table>BEER_ENTITY</table>

	<id>
		<field>
			<name>primaryKey</name>
			<type>uuid</type>
			<column>BEER_ENTITY_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>beerType</name>
			<documentation>What kind of beer this is</documentation>
			<type>string</type>
			<column>BEER_TYPE</column>
		</field>
	</fields>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/DefaultValueExample.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>DefaultValueExample</name>
	<namespace>org.bitbucket.askllc.fermenter.cookbook.domain</namespace>
	<documentation>A simple domain entity with a generated id field, fields of different types, and default values assigned to many of its fields</documentation>
	<table>DEFAULT_VALUE</table>

	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>DEFAULT_VALUE_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>name</name>
			<documentation>The friendly domain moniker</documentation>
			<type>string</type>
			<column>NAME</column>
			<defaultValue>Default name value</defaultValue>
		</field>
		<field>
			<name>type</name>
			<documentation>A simple domain classification</documentation>
			<type>string</type>
			<column>TYPE</column>
			<defaultValue>DefaultType</defaultValue>
		</field>
		<field>
			<name>theLong1</name>
			<documentation>A relevant number for this domain</documentation>
			<type>long</type>
			<column>LONG1</column>
			<defaultValue>31415926</defaultValue>
		</field>
		<field>
			<name>bigDecimalValue</name>
			<type>big_decimal</type>
			<column>BIG_DECIMAL</column>
			<defaultValue>3.141592645</defaultValue>
		</field>
		<field>
			<name>standardBoolean</name>
			<type>boolean</type>
			<column>STANDARD_BOOLEAN</column>
			<defaultValue>false</defaultValue>
		</field>
		<field>
			<name>aMESSYNameThatConfusesJson</name>
			<type>string</type>
			<column>MESSY_NAMED_FIELD</column>
			<defaultValue>true</defaultValue>
		</field>
		<field>
			<name>someInteger</name>
			<type>integer</type>
			<column>SOME_INTEGER</column>
			<defaultValue>1</defaultValue>
		</field>
		<field>
			<name>someTimestamp</name>
			<type>timestamp</type>
			<column>SOME_TIMESTAMP</column>
			<defaultValue>2022-07-16 04:26:19</defaultValue>
		</field>
		<field>
			<name>someDate</name>
			<type>date</type>
			<column>SOME_DATE</column>
			<defaultValue>2022-07-16</defaultValue>
		</field>
	</fields>
</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/LongKeyedEntity.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>LongKeyedEntity</name>
	<documentation>Entity that demonstrates uses a long as a generated value primary key</documentation>
	<table>LONG_KEYED_ENTITY</table>

	<id>
		<field>
			<name>id</name>
			<type>long</type>
			<column>LONG_KEYED_ENTITY_ID</column>
			<required>true</required>
			<generator>auto</generator>
		</field>
	</id>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/MappedSuperclassOneToManyChild.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>MappedSuperclassOneToManyChild</name>
	<documentation>Child entity of MappedSuperclassParent demonstrating an inheritance hierarchy with a mapped superclass strategy</documentation>
	<parent>
		<type>MappedSuperclassParent</type>
		<inheritanceStrategy>mapped-superclass</inheritanceStrategy>
	</parent>
	<table>MAPPED_SUPERCLASS_CHILD</table>
	
	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>MAPPED_SUPERCLASS_CHILD_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>someValue</name>
			<documentation>String value specific to this subclass</documentation>
			<type>string</type>
			<column>SOME_VALUE</column>
		</field>
	</fields>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/ServiceEntityExample.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>ServiceEntityExample</name>
	<documentation>Entity that demonstrates uses a generated value primary key</documentation>
	<table>SERVICE_ENTITY_EXAMPLE</table>

	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>SERVICE_ENTITY_EXAMPLE_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/SimpleDomain.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>SimpleDomain</name>
	<namespace>org.bitbucket.askllc.fermenter.cookbook.domain</namespace>
	<documentation>A simple domain entity with a generated id field, fields of different types, and a 1-M relation</documentation>
	<table>SIMPLE_DOMAIN</table>

	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>SIMPLE_DOMAIN_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>name</name>
			<documentation>The friendly domain moniker</documentation>
			<type>string</type>
			<column>NAME</column>
		</field>
		<field>
			<name>type</name>
			<documentation>A simple domain classification</documentation>
			<type>string</type>
			<column>TYPE</column>
		</field>
		<field>
			<name>theDate1</name>
			<documentation>An important date for this domain</documentation>
			<type>date</type>
			<column>DATE1</column>
		</field>
		<field>
			<name>theLong1</name>
			<documentation>A relevant number for this domain</documentation>
			<type>long</type>
			<column>LONG1</column>
		</field>
		<field>
			<name>anEnumeratedValue</name>
			<type>SimpleDomainEnumeration</type>
			<column>SIMPLE_DOMAIN_ENUM</column>
		</field>
		<field>
			<name>bigDecimalValue</name>
			<type>big_decimal</type>
			<column>BIG_DECIMAL_COLUMN</column>
		</field>
		<field>
			<name>standardBoolean</name>
			<type>boolean</type>
			<column>STANDARD_BOOLEAN</column>
		</field>
		<field>
			<name>numericBoolean</name>
			<type>numeric_boolean</type>
			<column>NUMERIC_BOOLEAN</column>
		</field>
	</fields>

	<associations>
		<relation>
			<type>SimpleDomainChild</type>
			<multiplicity>1-M</multiplicity>
			<fetchMode>lazy</fetchMode>
		</relation>
		<relation>
			<type>SimpleDomainEagerChild</type>
			<multiplicity>1-M</multiplicity>
		</relation>
	</associations>

</entity>
