=== TechnologyBrewery/fermenter/fermenter-mda/src/main/resources/fermenter-2-entity.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT entity (name, namespace?, documentation?, parent?, table?, lockStrategy?, id?, fields?, composites?, associations?, queries?)>
<!ELEMENT namespace (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT documentation (#PCDATA)>

<!ELEMENT parent (type, inheritanceStrategy?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT inheritanceStrategy (#PCDATA)>

<!ELEMENT table (#PCDATA)>
<!ELEMENT lockStrategy (#PCDATA)>
<!ATTLIST entity transient CDATA "false">

<!ELEMENT id (field)>

<!ELEMENT fields (field+)>
<!ELEMENT field (name, documentation?, type, project?, column?, required?, generator?, maxLength?, minLength?, maxValue?, minValue?, scale?, label?, format?)>
<!ELEMENT column (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT generator (#PCDATA)>
<!ELEMENT maxLength (#PCDATA)>
<!ELEMENT minLength (#PCDATA)>
<!ELEMENT maxValue (#PCDATA)>
<!ELEMENT minValue (#PCDATA)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT format (#PCDATA)>

<!ELEMENT associations (reference*,relation*)>
<!ELEMENT reference (name?, documentation?, type, project?, fk?,required?)>
<!ELEMENT project (#PCDATA)>
<!ELEMENT fk (name,source,column?)>
<!ELEMENT source (#PCDATA)>

<!ELEMENT relation (documentation?, type, fk?, multiplicity, fetchMode?)>
<!ELEMENT multiplicity (#PCDATA)>
<!ELEMENT fetchMode (#PCDATA)>

<!ELEMENT queries (query+)>
<!ELEMENT query (name, documentation?, criteria?, pagination?, statement)>
<!ELEMENT criteria (criterion+)>
<!ELEMENT criterion (name, documentation?, type)>
<!ELEMENT statement (#PCDATA)>
<!ELEMENT pagination (#PCDATA)>

<!ELEMENT composites (composite*)>
<!ELEMENT composite (type, name?, project?, prefix?, label)>
<!ELEMENT prefix (#PCDATA)>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/TableNameMismatch.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>TableNameMismatch</name>
	<documentation>Entity that demonstrates an error when table names drift between src/main resources and metamodel instances</documentation>
	<table>NEW_TABLE_NAME</table>

	<id>
		<field>
			<name>id</name>
			<type>integer</type>
			<column>NEW_TABLE_NAME_ID</column>
			<required>true</required>
			<generator>identity</generator>
		</field>
	</id>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-local-referencing-domain/src/main/resources/entities/Placeholder.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>Placeholder</name>
	<namespace>org.bitbucket.askllc.fermenter.cookbook.local.referencing.domain</namespace>
	<documentation>
		Generate an entity so we can not only test local call
		optimization
	</documentation>
	<table>PLACEHOLDER</table>

	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>PLACEHOLDER_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/CachedEntityExample.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
    <name>CachedEntityExample</name>
    <namespace>org.bitbucket.askllc.fermenter.cookbook.domain</namespace>
    <documentation>Cached Entity Example used for testing caching in rest client.</documentation>
    <table>CACHED_ENTITY_EXAMPLE</table>

    <id>
        <field>
            <name>id</name>
            <type>uuid</type>
            <column>CACHED_ENTITY_ID</column>
            <required>true</required>
            <generator>uuid</generator>
        </field>
    </id>

    <fields>
        <field>
            <name>name</name>
            <documentation>Name for the cached entity.</documentation>
            <type>string</type>
            <column>NAME</column>
            <defaultValue>Some Name</defaultValue>
        </field>
        <field>
        	<name>calculatedField</name>
        	<documentation>A field that is calculated on each save call</documentation>
            <type>integer</type>
            <column>CALCULATED_FIELD</column>
            <defaultValue>0</defaultValue>
        </field>
    </fields>
</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/ForeignKeyWithoutColumnDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>ForeignKeyWithoutColumnDefinition</name>
	<table>FK_WITHOUT_COLUMN_DEFINITION</table>
	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>FK_WITHOUT_COLUMN_DEFINITION_ID</column>
			<required>true</required>
			<generator>uuid</generator>
			<label>FK column is not defined in the relation</label>
		</field>
	</id>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-referencing-domain/src/main/resources/entities/LocalDomainTransientReference.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>LocalDomainTransientReference</name>
	<namespace>org.bitbucket.askllc.fermenter.cookbook.referencing.domain</namespace>
	<documentation>A local persistent domain with external reference to transient entity</documentation>
	<table>LOCAL_DOMAIN_TWO</table>

	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>LOCAL_DOMAIN_TWO_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>name</name>
			<documentation>The name of the entity</documentation>
			<type>string</type>
			<column>NAME</column>
		</field>
	</fields>

	<associations>
		<reference>
			<name>externalTransientReference</name>
			<type>ValidationTransientReferencedObject</type>
			<required>true</required>
		</reference>

	</associations>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/MappedSubclassB.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>MappedSubclassB</name>
	<documentation>Sub entity of MappedSuperclassParent demonstrating an inheritance hierarchy with a mapped superclass strategy</documentation>
	<parent>
		<type>MappedSuperclassParent</type>
		<inheritanceStrategy>mapped-superclass</inheritanceStrategy>
	</parent>
	<table>MAPPED_SUBCLASS_B</table>
	
	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>CHILD_B_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>childBType</name>
			<documentation>String value specific to this subclass</documentation>
			<type>string</type>
			<column>CHILD_B_TYPE</column>
		</field>
	</fields>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/ForeignKeyColumnCustomName.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>ForeignKeyColumnCustomName</name>
	<table>FK_CUSTOM_NAME</table>
	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>FK_CUSTOM_NAME</column>
			<required>true</required>
			<generator>uuid</generator>
			<label>Column unrelated to table name and doesn't have id</label>
		</field>
	</id>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/SimpleDomainChild.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/askllc/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>SimpleDomainChild</name>
	<documentation>Child end of the 1-M relationship with SimpleDomain</documentation>
	<table>SIMPLE_DOMAIN_CHILD</table>

	<id>
		<field>
			<name>id</name>
			<type>string</type>
			<column>SIMPLE_DOMAIN_CHILD_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>name</name>
			<documentation>Name of the child entity</documentation>
			<type>string</type>
			<column>NAME</column>
		</field>
	</fields>

</entity>
