=== TechnologyBrewery/fermenter/fermenter-mda/src/main/resources/fermenter-2-entity.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT entity (name, namespace?, documentation?, parent?, table?, lockStrategy?, id?, fields?, composites?, associations?, queries?)>
<!ELEMENT namespace (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT documentation (#PCDATA)>

<!ELEMENT parent (type, inheritanceStrategy?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT inheritanceStrategy (#PCDATA)>

<!ELEMENT table (#PCDATA)>
<!ELEMENT lockStrategy (#PCDATA)>
<!ATTLIST entity transient CDATA "false">

<!ELEMENT id (field)>

<!ELEMENT fields (field+)>
<!ELEMENT field (name, documentation?, type, project?, column?, required?, generator?, maxLength?, minLength?, maxValue?, minValue?, scale?, label?, format?)>
<!ELEMENT column (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ELEMENT generator (#PCDATA)>
<!ELEMENT maxLength (#PCDATA)>
<!ELEMENT minLength (#PCDATA)>
<!ELEMENT maxValue (#PCDATA)>
<!ELEMENT minValue (#PCDATA)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT format (#PCDATA)>

<!ELEMENT associations (reference*,relation*)>
<!ELEMENT reference (name?, documentation?, type, project?, fk?,required?)>
<!ELEMENT project (#PCDATA)>
<!ELEMENT fk (name,source,column?)>
<!ELEMENT source (#PCDATA)>

<!ELEMENT relation (documentation?, type, fk?, multiplicity, fetchMode?)>
<!ELEMENT multiplicity (#PCDATA)>
<!ELEMENT fetchMode (#PCDATA)>

<!ELEMENT queries (query+)>
<!ELEMENT query (name, documentation?, criteria?, pagination?, statement)>
<!ELEMENT criteria (criterion+)>
<!ELEMENT criterion (name, documentation?, type)>
<!ELEMENT statement (#PCDATA)>
<!ELEMENT pagination (#PCDATA)>

<!ELEMENT composites (composite*)>
<!ELEMENT composite (type, name?, project?, prefix?, label)>
<!ELEMENT prefix (#PCDATA)>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/UuidKeyedEntity.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>UuidKeyedEntity</name>
	<documentation>Entity that demonstrates uses a UUID as a generated value primary key</documentation>
	<table>UUID_KEYED_ENTITY</table>

	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>UUID_KEYED_ENTITY_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/MappedSuperclassParent.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>MappedSuperclassParent</name>
	<documentation>Parent entity demonstrating an inheritance hierarchy with a mapped superclass strategy</documentation>

	<fields>
		<field>
			<name>commonStringValue</name>
			<documentation>Persistent string value that is shared across subclasses</documentation>
			<type>string</type>
			<column>COMMON_STRING_VALUE</column>
		</field>
	</fields>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/MappedSubclassA.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>MappedSubclassA</name>
	<documentation>Sub entity of MappedSuperclassParent demonstrating an inheritance hierarchy with a mapped superclass strategy</documentation>
	<parent>
		<type>MappedSuperclassParent</type>
		<inheritanceStrategy>mapped-superclass</inheritanceStrategy>
	</parent>
	<table>MAPPED_SUBCLASS_A</table>
	
	<id>
		<field>
			<name>id</name>
			<type>uuid</type>
			<column>CHILD_A_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>childAType</name>
			<documentation>String value specific to this subclass</documentation>
			<type>string</type>
			<column>CHILD_A_TYPE</column>
		</field>
	</fields>
	
	<associations>
		<reference>
			<name>refToIntKeyedEntity</name>
			<type>IntegerKeyedEntity</type>
			<required>true</required>
		</reference>
	</associations>
</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/IdentityKeyedEntity.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>IdentityKeyedEntity</name>
	<documentation>Entity that demonstrates uses of an IDENTITY as a generated value primary key</documentation>
	<table>IDENTITY_KEYED_ENTITY</table>

	<id>
		<field>
			<name>id</name>
			<type>integer</type>
			<column>IDENTITY_KEYED_ENTITY_ID</column>
			<required>true</required>
			<generator>identity</generator>
		</field>
	</id>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/BusinessKeyedExample.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>BusinessKeyedExample</name>
	<namespace>org.bitbucket.askllc.fermenter.cookbook.domain</namespace>
	<documentation>Entity to help with the business key patterns that
		coordinate with a programmatic primary key</documentation>
	<table>BUSINESS_KEYED_EXAMPLE</table>

	<id>
		<field>
			<name>primaryKey</name>
			<type>uuid</type>
			<column>BUSINESS_KEYED_EXAMPLE_ID</column>
			<required>true</required>
			<generator>uuid</generator>
		</field>
	</id>

	<fields>
		<field>
			<name>businessKey</name>
			<documentation>A business key that is required</documentation>
			<type>string</type>
			<column>BUSINESS_KEY</column>
			<required>true</required>
		</field>
		<field>
			<name>selector</name>
			<documentation>A field that can be used for easy find by example queries</documentation>
			<type>string</type>
			<column>SELECTOR</column>
		</field>
	</fields>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/TransientSubEntityExample.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity transient="true">
	<name>TransientSubEntityExample</name>
	<documentation>A non-persistent entity</documentation>
	
	<parent>
		<!-- TODO: doesn't seem to work w/ transient entities... -->
		<type>TransientEntityExample</type>
		<inheritanceStrategy>mapped-superclass</inheritanceStrategy>
	</parent>	

	<fields>
		<field>
			<name>someOtherName</name>
			<documentation>The friendly domain moniker</documentation>
			<type>string</type>
		</field>
	</fields>

</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/ValidationReferenceExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/askllc/fermenter/downloads/fermenter-2-entity.dtd">

<entity>
	<name>ValidationReferenceExample</name>
	<table>VALIDATION_REF_EXAMPLE</table>
  	<id>
  		<field>
       		<name>id</name>
      		<type>string</type>
       		<column>VALIDATION_REF_EXAMPLE_ID</column>
       		<required>true</required>
       		<generator>uuid</generator>
       		<label>validation reference example id</label>
		</field>
	</id>
	<fields>
   		<field>
       		<name>someDataField</name>
       		<type>string</type>
       		<column>SOME_DATA_FIELD</column>
       		<label>some data field</label>
   		</field>
	</fields>
	<associations>
		<reference>
			<name>requiredReference</name>
			<type>ValidationReferencedObject</type>
			<fk>
				<name>id</name>
				<source>id</source>
				<column>VALIDATION_REF_OBJECT_ID</column>
			</fk>
			<required>true</required>
		</reference>
	</associations>
</entity>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/entities/TransientChildEntity.xml
<?xml version="1.0"?>
<!DOCTYPE entity PUBLIC "-//FERMENTER//DTD ENTITY//EN" "https://bitbucket.org/cpointe/fermenter/downloads/fermenter-2-entity.dtd">

<entity transient="true">
	<name>TransientChildEntity</name>
	<documentation>A non-persistent child entity</documentation>

	<fields>
		<field>
			<name>name</name>
			<documentation>The friendly domain moniker</documentation>
			<type>string</type>
		</field>
	</fields>

</entity>
