=== TechnologyBrewery/fermenter/fermenter-mda/src/main/resources/types.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT java (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (name,java)>
<!ELEMENT types (type+)>

=== TechnologyBrewery/fermenter/fermenter-java-mda/target/classes/types.xml
<?xml version="1.0"?>
<!DOCTYPE types PUBLIC "-//ATLAS//DTD TYPES//EN" "http://atlas.tigris.org/svn/atlas/trunk/atlas-mda/src/main/resources/types.dtd">

<types>
	<type>
		<name>string</name>
		<java>java.lang.String</java>
	</type>
	<type>
		<name>date</name>
		<java>java.util.Date</java>
	</type>
	<type>
		<name>timestamp</name>
		<java>java.sql.Timestamp</java>
	</type>
	<type>
		<name>long</name>
		<java>java.lang.Long</java>
	</type>
	<type>
		<name>integer</name>
		<java>java.lang.Integer</java>
	</type>
	<type>
		<name>boolean</name>
		<java>java.lang.Boolean</java>
	</type>
	<type>
		<name>big_decimal</name>
		<java>java.math.BigDecimal</java>
	</type>
	<type>
		<name>character</name>
		<java>java.lang.String</java>
	</type>
	<type>
		<name>blob</name>
		<java>java.sql.Blob</java>
	</type>
</types>

=== TechnologyBrewery/fermenter/stout/stout-spring-mda/src/main/resources/types.xml
<?xml version="1.0"?>
<!DOCTYPE types PUBLIC "-//FERMENTER//DTD TYPES//EN" "https://bitbucket.org/askllc/fermenter/downloads/types.dtd">

<types>
	<type>
		<name>string</name>
		<java>java.lang.String</java>
	</type>
	<type>
		<name>date</name>
		<java>java.util.Date</java>
	</type>
	<type>
		<name>timestamp</name>
		<java>java.sql.Timestamp</java>
	</type>
	<type>
		<name>long</name>
		<java>java.lang.Long</java>
	</type>
	<type>
		<name>integer</name>
		<java>java.lang.Integer</java>
	</type>
	<type>
		<name>boolean</name>
		<java>java.lang.Boolean</java>
	</type>
	<type>
		<name>numeric_boolean</name>
		<java>java.lang.Boolean</java>
	</type>
	<type>
		<name>big_decimal</name>
		<java>java.math.BigDecimal</java>
	</type>
	<type>
		<name>character</name>
		<java>java.lang.String</java>
	</type>
	<type>
		<name>blob</name>
		<java>java.sql.Blob</java>
	</type>
	<type>
		<name>geospatial_point</name>
		<java>com.vividsolutions.jts.geom.Point</java>
	</type>
</types>
