=== TechnologyBrewery/fermenter/fermenter-mda/target/classes/enumeration.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT enumeration (name,type,enums)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>

<!ELEMENT enums (enum+)>

<!ELEMENT enum (name,value?)>
<!ELEMENT value (#PCDATA)>

=== TechnologyBrewery/fermenter/stout/stout-cookbook/stout-cookbook-domain/src/main/resources/enumerations/SimpleDomainEnumeration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE enumeration PUBLIC "-//FERMENTER//DTD ENUMERATION//EN" "https://bitbucket.org/askllc/fermenter/downloads/enumeration.dtd">

<enumeration>
	<name>SimpleDomainEnumeration</name>
	<type>named</type>
	<enums>
		<enum>
			<name>FIRST</name>
		</enum>
		<enum>
			<name>SECOND</name>
		</enum>
		<enum>
			<name>THIRD</name>
		</enum>
		<enum>
			<name>FOURTH</name>
		</enum>
	</enums>
</enumeration>
