=== TechnologyBrewery/fermenter/fermenter-mda/target/classes/profiles.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT profiles (profile+)>

<!ELEMENT profile (target*,include*)>
<!ATTLIST profile name CDATA #REQUIRED>
<!ATTLIST profile extends CDATA #IMPLIED>

<!ELEMENT target EMPTY>
<!ATTLIST target name CDATA #REQUIRED>

<!ELEMENT include EMPTY>
<!ATTLIST include name CDATA #REQUIRED>

=== TechnologyBrewery/fermenter/fermenter-mda/src/main/resources/profiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profiles PUBLIC "-//ATLAS//DTD PROFILES//EN" "http://atlas.tigris.org/svn/atlas/trunk/atlas-mda/src/main/resources/profiles.dtd">

<profiles>
	<profile name="html-docs">
		<target name="serviceHtml"/>
		<target name="entityHtml"/>
		<target name="entityListHtml"/>
		<target name="enumerationHtml"/>
		<target name="metadataHtml"/>
		<target name="metadataCss"/>
	</profile>
</profiles>

=== TechnologyBrewery/fermenter/fermenter-ejb-mda/src/main/resources/profiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profiles PUBLIC "-//FERMENTER//DTD PROFILES//EN" "https://bitbucket.org/askllc/fermenter/downloads/profiles.dtd">

<profiles>

	<profile name="ejbFactories">
		<target name="ejbServiceFactory"/>
	</profile>

	<profile name="java-service-session-beans" extends="ejbFactories">
		<target name="serviceSessionBeanRemoteInterfaces"/>
		<target name="serviceSessionBeanLocalInterfaces"/>
		<target name="serviceSessionBeanHomeInterfaces"/>
		<target name="serviceSessionBeanLocalHomeInterfaces"/>
		<target name="serviceSessionBeanObjects"/>
		<target name="sessionBeanServiceDelegateObjects"/>
	</profile>

	<profile name="java-entity-maintenance-session-beans-service-only" extends="ejbFactories">
		<target name="entityMaintenanceServiceLocal"/>
		<target name="entityMaintenanceServiceBean"/>
	</profile>

	<profile name="java-entity-maintenance-session-beans" extends="java-entity-maintenance-session-beans-service-only">
		<target name="sessionBeanEntityMaintenanceServiceDelegateImpl"/>
	</profile>

</profiles>

=== TechnologyBrewery/fermenter/fermenter-hibernate-mda/src/main/resources/profiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profiles PUBLIC "-//FERMENTER//DTD PROFILES//EN" "https://bitbucket.org/askllc/fermenter/downloads/profiles.dtd">

<profiles>
	<profile name="java-hibernate">
		<target name="baseDataAccessObjectHibernateImpls"/>
		<target name="dataAccessObjectHibernateImpls"/>
		<target name="hibernateMappings"/>
		<target name="daoFactoryHibernate"/>
		<target name="factoryPropertiesHibernate"/>
		<target name="hibernateConfigXml"/>
		<target name="hibernateProperties"/>
		<target name="resourcesPropertiesHibernate"/>
	</profile>
</profiles>

=== TechnologyBrewery/fermenter/fermenter-hibernate-mda/target/classes/profiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profiles PUBLIC "-//ATLAS//DTD PROFILES//EN" "http://atlas.tigris.org/svn/atlas/trunk/atlas-mda/src/main/resources/profiles.dtd">

<profiles>
	<profile name="java-hibernate">
		<target name="enumerationHibernateUserTypeObjects"/>
		<target name="dataAccessObjectHibernateImpls"/>
		<target name="ddlAntTaskGenerator"/>
		<target name="hibernateMappings"/>
		<target name="daoFactoryHibernate"/>
		<target name="factoryPropertiesHibernate"/>
		<target name="hibernateConfigXml"/>
		<target name="hibernateProperties"/>
		<target name="resourcesPropertiesHibernate"/>
	</profile>
</profiles>

=== TechnologyBrewery/fermenter/stout/stout-spring-mda/src/main/resources/profiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profiles PUBLIC "-//FERMENTER//DTD PROFILES//EN" "https://bitbucket.org/askllc/fermenter/downloads/profiles.dtd">

<profiles>
	<profile name="business-objects-and-services">
		<target name="baseBusinessObjects"/>
		<target name="businessObjects"/>
		<target name="dataAccessRepositories"/>
		<target name="enumerations"/>
		<target name="baseTransferObjectJacksonMixIns"/>
		<target name="transferObjectJacksonMixIns"/>
		<target name="objectMapperManager"/>
		<target name="jacksonObjectMapperResteasyProvider"/>
		
		<target name="baseRestServiceInterfaces"/>
		<target name="restServiceInterfaces"/>
		<target name="baseServiceImpl"/>
		<target name="serviceImpl"/>
		
		<target name="messageProperties"/>
		<target name="springContext"/>
		<target name="jpaProperties"/>	
		<target name="dataSourceProperties"/>			
	</profile>
	<profile name="entity-maintenance-services">
		<target name="entityMaintenanceServiceImpls"/>
		<target name="restEntityMaintenanceServiceInterfaces"/>
	</profile>	    
</profiles>

=== TechnologyBrewery/fermenter/fermenter-java-mda/src/main/resources/profiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profiles PUBLIC "-//FERMENTER//DTD PROFILES//EN" "https://bitbucket.org/askllc/fermenter/downloads/profiles.dtd">

<profiles>
	
	<profile name="java-interfaces">
		<target name="transferObjectFactoryInterface"/>
		<target name="businessObjectFactoryInterface"/>
		<target name="serviceDelegateInterfaces"/>
		<target name="serviceInterfaces"/>
		<target name="serviceFactoryInterface"/>
		<target name="serviceDelegateFactoryInterface"/>
		<target name="dataAccessObjectFactoryInterface"/>
		<target name="dataAccessObjects"/>
		<target name="entityMaintenanceService"/>
		<target name="entityMaintenanceServiceDelegateInterface"/>
	</profile>
	
	<profile name="java-base" extends="java-interfaces">
		<target name="baseBusinessObjects"/>
		<target name="businessObjects"/>
		<target name="businessObjectFactory"/>
		<target name="businessObjectFactoryJava"/>
		<target name="primaryKeys"/>
		<target name="enumerationObjects"/>
		<target name="transferObjects"/>
		<target name="transferObjectFactory"/>
		<target name="transferObjectFactoryJava"/>
		<target name="transferObjectAssemblers"/>
		<target name="serviceResponseIteratorObjects"/>
		<target name="entityServiceResponseObjects"/>
		<target name="entityCollectionServiceResponseObjects"/>
		<target name="transferObjectComposites"/>				
		<target name="baseBusinessObjectComposites"/>					
		<target name="businessObjectComposites"/>
		<target name="dataAccessObjectFactory"/>
		<target name="serviceImplObjects"/>
		<target name="serviceBaseImplObjects"/>
		<target name="serviceFactory"/>	
		<target name="serviceFactoryJava"/>				
		<target name="serviceDelegateFactory"/>	
		<target name="serviceDelegateFactoryJava"/>								
		<target name="packageProperties"/>
		<target name="messageProperties"/>
		<target name="entityMaintenanceServiceImpl"/>
		<target name="factoryPropertiesPojo"/>
	</profile>
	
	<profile name="java-pojo-services" extends="java-base">		
		<target name="pojoServiceDelegateObjects"/>
		<target name="pojoEntityMaintenanceServiceDelegate"/>
		<target name="serviceDelegateFactoryJava"/>
	</profile>
	
</profiles>

=== TechnologyBrewery/fermenter/fermenter-objective-c-mda/src/main/resources/profiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profiles PUBLIC "-//FERMENTER//DTD PROFILES//EN" "https://bitbucket.org/askllc/fermenter/downloads/profiles.dtd">

<profiles>
	<profile name="objective-c-base">
		<target name="objective-c-entity-header"/>
		<target name="objective-c-entity-source"/>
		<target name="objective-c-enumeration-header"/>
		<target name="objective-c-enumeration-source"/>
		<target name="objective-c-service-response-header"/>
		<target name="objective-c-service-response-source"/>
	</profile>
</profiles>
